import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster"
//import Navbar from "@/components/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// why do we need two layout files 
/*export default function RootLayout({ children, }:Readonly<{children:React.ReactNode;}>) {
  return (
    <html lang="en">
      <AuthProvider></AuthProvider>
      <body
        className={inter.className}>
          </Navbar>
        {children}
        <Toaster />
      </body>
    </html>
  );
}*/
